### ISSUE TITLE
FastSQIsignHD

### ISSUE THREAD

**Issue by cryptoquick** [SQISign/the-sqisign#2]
An improvement on SQIsign has been proposed which can get NIST-I signatures down to 109 bytes, amongst other performance and improvements in the simplicity and analysis of the implementation.

Unfortunately, I can't seem to find the code for that online. I'm wondering if it might make sense to update the implementation here with the improvements described in the paper:

https://link.springer.com/chapter/10.1007/978-3-031-58716-0_1

**Comment by cryptoquick** [comment]
There are still innovations occurring in SQIsign it seems... Here's an another implementation, called SQIsign2D-West:
https://eprint.iacr.org/2024/760.pdf

The only problem with that proposal is that the signature size is larger than than FastSQIsignHD, which is the principal constraint for use in blockchain applications.

NIST-I:

SQIsign: 177 bytes
FastSQIsignHD: 107 bytes
SQIsign2D-West: 148 bytes

This is also assuming NIST-I security is suitable for securing amounts in the billions of dollars for periods of years at a time.

**Comment by defeo** [comment]
Hi @cryptoquick , the code for SQIsignHD is here: https://github.com/Pierrick-Dartois/SQISignHD-lib

**Comment by cryptoquick** [comment]
@defeo Thanks a ton! I'll close this.

**Comment by defeo** [comment]
The SQIsign team is carefully considering the recent advances on isogeny-based signatures. In case there was a decision to update the spec and code, we will announce it on the NIST pqc forum.
